export const ActionTypes = {
  SET_REPAS: "SET_REPAS",
  
  SET_COMMAND: "SET_COMMAND",
  SELECTED_COMMAND: "SELECTED_COMMAND",

  SELECTED_REPAS: "SELECTED_REPAS",
  REMOVE_SELECTED_REPAS: "REMOVE_SELECTED_REPAS",

  ADD_TO_CART : "ADD_TO_CART",
  DELETE_FROM_CART : "DELETE_FROM_CART",
};
